import NavItem from "@/components/Atoms/NavItem";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import GooseButton from "@/components/Atoms/GooseButton";
import name from "../../public/name.svg";
import Image from "next/image";
import Link from "next/link";
import AppFooter from "@/components/Molecules/AppFooter";
import AppHeader from "@/components/Molecules/AppHeader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Gloria!",
  description: "Generated by Gloria",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AppHeader />
        <div className="flex justify-center">{children}</div>
        <AppFooter />
      </body>
    </html>
  );
}
